version: '3'
services:
  fb-hide:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fb-hide
    restart: always
    # depends_on:
    #   - db
    environment:
      - PORT=6000
      - DB_TYPE=mysql
      - DB_HOST=91.98.138.98
      - DB_PORT=3306
      - DB_USER_NAME=root
      - DB_PASSWORD=HoangChuong@1111
      - DB_DATABASE=crawl-fb
      - NODE_OPTIONS=--max-old-space-size=4096
      # redis
      - REDIS_HOST=91.98.138.98
      - REDIS_PORT=6379
      - REDIS_TYPE=single
    ports:
      - '6000:6000'
